version: '3.8'

services:
  app:
    container_name: cm-box
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./storage:/app/storage
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3001
    networks:
      - cm-box-network

networks:
  cm-box-network:
    name: cm-box-network 