version: '3.8'

services:
  app:
    container_name: cm-box
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
      cache_from:
        - node:18-alpine
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - storage:/app/storage
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3001
      - NPM_CONFIG_LOGLEVEL=error
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - cm-box-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  storage:
    name: cm-box-storage

networks:
  cm-box-network:
    name: cm-box-network